# -*- coding: utf-8 -*-
"""Predictive Market Modelling(1)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7Rq-L5ufY3pptxMTUogJee2TSC8AnZr
"""

from google.colab import files

uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data.csv")

df.head()

print(df.shape)

print(df.info())

print(df.describe())

print(df.isnull().sum())

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

X = df.drop(["Price", "ID"], axis=1)
y = df["Price"]

X = X.fillna(X.mean(numeric_only=True))
X = pd.get_dummies(X, drop_first=True)

X = X.values
y = y.values.reshape(-1,1)

ones = np.ones((X.shape[0],1))
X = np.hstack((ones, X))

beta = np.linalg.inv(X.T @ X) @ X.T @ y

print(beta)

y_pred = X @ beta

mse = np.mean((y - y_pred)**2)

print("MSE =", mse)

rss = np.sum((y - y_pred)**2)

print("RSS =", rss)

plt.figure(figsize=(8,6))
plt.scatter(y, y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted")
plt.show()

residuals = y - y_pred

plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals)
plt.axhline(y=0)
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.show()

"""BONUS TASK

"""

# Standardization

X_std = (X[:,1:] - np.mean(X[:,1:], axis=0)) / np.std(X[:,1:], axis=0)

# Add bias column again

ones = np.ones((X_std.shape[0],1))

X_std = np.hstack((ones, X_std))

# Linear Regression after standardization

beta_std = np.linalg.inv(X_std.T @ X_std) @ X_std.T @ y

y_pred_std = X_std @ beta_std

# MSE and RSS

mse_std = np.mean((y - y_pred_std)**2)

rss_std = np.sum((y - y_pred_std)**2)

print("MSE after standardization =", mse_std)
print("RSS after standardization =", rss_std)

"""Bonus Task 1: Standardization

The independent variables were standardized to have mean 0 and standard deviation 1.

After standardization:

MSE = 47777.37
RSS = 23888683.96

The model performance remained similar, indicating that standardization did not significantly affect prediction accuracy for this dataset.
"""

print(df.columns)

# Polynomial Features

X_poly = pd.DataFrame()

# Fill missing values in 'Square_Feet' before creating polynomial features
df_square_feet_filled = df["Square_Feet"].fillna(df["Square_Feet"].mean())

# Standardize Square_Feet for better numerical stability in polynomial regression
square_feet_standardized = (df_square_feet_filled - df_square_feet_filled.mean()) / df_square_feet_filled.std()

X_poly["Square_Feet"] = square_feet_standardized
X_poly["Square_Feet_Squared"] = square_feet_standardized ** 2

y_poly = df["Price"].values.reshape(-1,1)

X_poly = X_poly.values

ones = np.ones((X_poly.shape[0],1))

X_poly = np.hstack((ones, X_poly))

beta_poly = np.linalg.inv(X_poly.T @ X_poly) @ X_poly.T @ y_poly

y_pred_poly = X_poly @ beta_poly

mse_poly = np.mean((y_poly - y_pred_poly)**2)

rss_poly = np.sum((y_poly - y_pred_poly)**2)

print("Polynomial MSE =", mse_poly)

print("Polynomial RSS =", rss_poly)

print("Linear Regression MSE =", mse)

print("Polynomial Regression MSE =", mse_poly)

print()

print("Linear Regression RSS =", rss)

print("Polynomial Regression RSS =", rss_poly)

plt.figure(figsize=(8,6))

plt.scatter(y_poly, y_pred_poly)

plt.xlabel("Actual Prices")

plt.ylabel("Predicted Prices")

plt.title("Polynomial Regression: Actual vs Predicted")

plt.show()

"""Bonus Task 2: Polynomial Regression

Polynomial features were created using the Square_Feet variable by adding a squared term.

After training the polynomial regression model, the performance metrics were:

Polynomial MSE = 1027208.39
Polynomial RSS = 513604195.59

These values are higher than those of the linear regression model.

Therefore, for this dataset, the simple linear regression model performed better than the polynomial regression model. Adding polynomial features did not improve prediction accuracy.

Conclusion

A linear regression model was implemented from scratch using the matrix-based method.

The model was evaluated using MSE and RSS and showed good agreement between actual and predicted house prices.

Standardization of the independent variables did not significantly affect model performance.

Polynomial regression using Square_Feet and its squared term was also tested. However, the polynomial model produced higher MSE and RSS values than the linear model, indicating poorer performance on this dataset.

Hence, the linear regression model was the most suitable model among the methods tested.
"""
